import type { Team, Player, Pos, FormationKey, Manager } from './types'

let pid = 0
function p(
  name: string,
  posStr: string,
  rating: number,
  nationality: string,
  club: string,
  trophies?: string[],
  trivia?: string,
): Player {
  pid += 1
  return {
    id: `pl-${pid}`,
    name,
    positions: posStr.split('/').map((s) => s.trim() as Pos),
    rating,
    nationality,
    club,
    trophies,
    trivia,
  }
}

function mgr(
  name: string,
  nationality: string,
  signatureFormation: FormationKey,
  team: string,
): Manager {
  return { id: `mgr-${team}`.replace(/\s+/g, '-').toLowerCase(), name, nationality, signatureFormation, team }
}

export const TEAMS: Team[] = [
  {
    id: 'italy-1982',
    name: 'Italy',
    type: 'national',
    year: 1982,
    era: '80s',
    manager: mgr('Enzo Bearzot', 'Italy', '3-5-2', 'Italy 1982'),
    players: [
      p('Dino Zoff', 'GK', 91, 'Italy', 'Italy', ['1982 World Cup', 'Captain'], 'Oldest player to win the World Cup at 40, captaining Italy to glory in 1982.'),
      p('Claudio Gentile', 'CB', 89, 'Italy', 'Italy', ['1982 World Cup'], 'Legendary man-marker who famously shackled Maradona and Zico in 1982.'),
      p('Gaetano Scirea', 'CB/SW', 93, 'Italy', 'Italy', ['1982 World Cup'], 'The elegant sweeper, a model of fair play who won every major trophy.'),
      p('Antonio Cabrini', 'LB', 90, 'Italy', 'Italy', ['1982 World Cup'], 'Attacking full-back nicknamed "Bell\u2019Antonio".'),
      p('Marco Tardelli', 'CM', 89, 'Italy', 'Italy', ['1982 World Cup'], 'His unforgettable goal celebration in the final defined the tournament.'),
      p('Bruno Conti', 'RW', 90, 'Italy', 'Italy', ['1982 World Cup'], 'Dazzling winger and creative engine of the 1982 champions.'),
      p('Paolo Rossi', 'ST', 94, 'Italy', 'Italy', ['1982 World Cup', '1982 Golden Boot', '1982 Ballon d\u2019Or'], 'Top scorer of the 1982 World Cup with a stunning hat-trick vs Brazil.'),
      p('Giancarlo Antognoni', 'AM', 88, 'Italy', 'Italy', ['1982 World Cup'], 'Graceful playmaker, a Fiorentina icon.'),
    ],
  },
  {
    id: 'argentina-1986',
    name: 'Argentina',
    type: 'national',
    year: 1986,
    era: '80s',
    manager: mgr('Carlos Bilardo', 'Argentina', '3-5-2', 'Argentina 1986'),
    players: [
      p('Nery Pumpido', 'GK', 83, 'Argentina', 'Argentina', ['1986 World Cup']),
      p('Oscar Ruggeri', 'CB', 88, 'Argentina', 'Argentina', ['1986 World Cup']),
      p('Jos\u00e9 Luis Brown', 'CB', 85, 'Argentina', 'Argentina', ['1986 World Cup'], 'Scored the opening goal in the 1986 final.'),
      p('Sergio Batista', 'CM', 86, 'Argentina', 'Argentina', ['1986 World Cup']),
      p('Jorge Burruchaga', 'CM', 89, 'Argentina', 'Argentina', ['1986 World Cup'], 'Scored the winning goal in the 1986 final.'),
      p('H\u00e9ctor Enrique', 'RM', 84, 'Argentina', 'Argentina', ['1986 World Cup']),
      p('Jorge Valdano', 'ST', 89, 'Argentina', 'Argentina', ['1986 World Cup']),
      p('Diego Maradona', 'AM/ST', 99, 'Argentina', 'Argentina', ['1986 World Cup', 'Golden Ball', 'Goal of the Century'], 'Authored the greatest individual World Cup run ever, dragging Argentina to the 1986 title.'),
    ],
  },
  {
    id: 'ac-milan-1990',
    name: 'AC Milan',
    type: 'club',
    year: 1990,
    era: '90s',
    manager: mgr('Arrigo Sacchi', 'Italy', '4-4-2', 'AC Milan 1990'),
    players: [
      p('Giovanni Galli', 'GK', 85, 'Italy', 'AC Milan', ['European Cup']),
      p('Franco Baresi', 'CB/SW', 95, 'Italy', 'AC Milan', ['European Cup', 'Serie A'], 'The greatest sweeper in history and heart of Sacchi\u2019s pressing machine.'),
      p('Alessandro Costacurta', 'CB', 90, 'Italy', 'AC Milan', ['European Cup']),
      p('Paolo Maldini', 'LB', 96, 'Italy', 'AC Milan', ['5x European Cup/UCL'], 'The eternal defender, a one-club legend for 25 years.'),
      p('Mauro Tassotti', 'RB', 89, 'Italy', 'AC Milan', ['European Cup']),
      p('Frank Rijkaard', 'CM/DM', 93, 'Netherlands', 'AC Milan', ['European Cup', 'Euro 1988'], 'Complete midfielder, one of the Dutch trio.'),
      p('Carlo Ancelotti', 'CM', 88, 'Italy', 'AC Milan', ['European Cup']),
      p('Roberto Donadoni', 'RM/LM', 90, 'Italy', 'AC Milan', ['European Cup']),
      p('Ruud Gullit', 'AM/ST', 94, 'Netherlands', 'AC Milan', ['Ballon d\u2019Or 1987', 'European Cup', 'Euro 1988'], 'Dreadlocked talisman, Ballon d\u2019Or winner and Dutch captain.'),
      p('Marco van Basten', 'ST', 96, 'Netherlands', 'AC Milan', ['3x Ballon d\u2019Or', 'European Cup', 'Euro 1988'], 'Scored the iconic volley in the Euro 1988 final; one of the greatest strikers ever.'),
    ],
  },
  {
    id: 'west-germany-1990',
    name: 'West Germany',
    type: 'national',
    year: 1990,
    era: '90s',
    manager: mgr('Franz Beckenbauer', 'West Germany', '3-5-2', 'West Germany 1990'),
    players: [
      p('Bodo Illgner', 'GK', 87, 'West Germany', 'West Germany', ['1990 World Cup']),
      p('Klaus Augenthaler', 'CB', 89, 'West Germany', 'West Germany', ['1990 World Cup']),
      p('J\u00fcrgen Kohler', 'CB', 91, 'West Germany', 'West Germany', ['1990 World Cup']),
      p('Andreas Brehme', 'LB', 92, 'West Germany', 'West Germany', ['1990 World Cup'], 'Scored the winning penalty in the 1990 final.'),
      p('Lothar Matth\u00e4us', 'CM/AM', 96, 'West Germany', 'West Germany', ['1990 World Cup', 'Ballon d\u2019Or 1990'], 'Captain and engine of the 1990 champions.'),
      p('Thomas H\u00e4\u00dfler', 'RM', 90, 'West Germany', 'West Germany', ['1990 World Cup']),
      p('J\u00fcrgen Klinsmann', 'ST', 92, 'West Germany', 'West Germany', ['1990 World Cup', 'Euro 1996']),
      p('Rudi V\u00f6ller', 'ST', 91, 'West Germany', 'West Germany', ['1990 World Cup']),
    ],
  },
  {
    id: 'brazil-1994',
    name: 'Brazil',
    type: 'national',
    year: 1994,
    era: '90s',
    manager: mgr('Carlos Alberto Parreira', 'Brazil', '4-4-2', 'Brazil 1994'),
    players: [
      p('Taffarel', 'GK', 87, 'Brazil', 'Brazil', ['1994 World Cup']),
      p('Aldair', 'CB', 89, 'Brazil', 'Brazil', ['1994 World Cup']),
      p('M\u00e1rcio Santos', 'CB', 86, 'Brazil', 'Brazil', ['1994 World Cup']),
      p('Jorginho', 'RB', 90, 'Brazil', 'Brazil', ['1994 World Cup']),
      p('Branco', 'LB', 87, 'Brazil', 'Brazil', ['1994 World Cup']),
      p('Mauro Silva', 'CM', 89, 'Brazil', 'Brazil', ['1994 World Cup']),
      p('Dunga', 'CM', 91, 'Brazil', 'Brazil', ['1994 World Cup'], 'Captain who lifted Brazil\u2019s fourth star.'),
      p('Zinho', 'AM', 85, 'Brazil', 'Brazil', ['1994 World Cup']),
      p('Bebeto', 'ST', 90, 'Brazil', 'Brazil', ['1994 World Cup'], 'Famous for the cradle-rocking celebration.'),
      p('Rom\u00e1rio', 'ST', 97, 'Brazil', 'Brazil', ['1994 World Cup', '1994 Ballon d\u2019Or'], 'The clinical genius who fired Brazil to the 1994 title.'),
    ],
  },
  {
    id: 'france-1998',
    name: 'France',
    type: 'national',
    year: 1998,
    era: '90s',
    manager: mgr('Aim\u00e9 Jacquet', 'France', '4-3-3', 'France 1998'),
    players: [
      p('Fabien Barthez', 'GK', 89, 'France', 'France', ['1998 World Cup', 'Euro 2000']),
      p('Laurent Blanc', 'CB', 90, 'France', 'France', ['1998 World Cup']),
      p('Marcel Desailly', 'CB', 92, 'France', 'France', ['1998 World Cup', 'UCL']),
      p('Bixente Lizarazu', 'LB', 89, 'France', 'France', ['1998 World Cup']),
      p('Lilian Thuram', 'RB', 91, 'France', 'France', ['1998 World Cup'], 'Scored his only two France goals in the 1998 semifinal.'),
      p('Didier Deschamps', 'CM', 90, 'France', 'France', ['1998 World Cup'], 'Captain in 1998, later a World Cup-winning manager.'),
      p('Emmanuel Petit', 'CM', 88, 'France', 'France', ['1998 World Cup']),
      p('Patrick Vieira', 'CM', 87, 'France', 'France', ['1998 World Cup']),
      p('Zinedine Zidane', 'AM', 97, 'France', 'France', ['1998 World Cup', 'Ballon d\u2019Or 1998'], 'Scored twice in the 1998 final; one of the greatest playmakers ever.'),
      p('Youri Djorkaeff', 'AM/LW', 89, 'France', 'France', ['1998 World Cup']),
      p('Thierry Henry', 'ST', 86, 'France', 'France', ['1998 World Cup'], 'Emerging star who became France\u2019s all-time top scorer.'),
    ],
  },
  {
    id: 'turkey-2002',
    name: 'Turkey',
    type: 'national',
    year: 2002,
    era: '00s',
    manager: mgr('\u015eenol G\u00fcne\u015f', 'Turkey', '4-4-2', 'Turkey 2002'),
    players: [
      p('R\u00fc\u015ft\u00fc Re\u00e7ber', 'GK', 90, 'Turkey', 'Turkey', ['2002 WC Bronze'], 'Iconic keeper, war-paint and all, of Turkey\u2019s greatest generation.'),
      p('Alpay \u00d6zalan', 'CB', 87, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('B\u00fclent Korkmaz', 'CB', 85, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('Fatih Akyel', 'RB', 83, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('Hakan \u00dcnsal', 'LB', 84, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('Tugay Kerimo\u011flu', 'CM', 88, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('Y\u0131ld\u0131ray Ba\u015ft\u00fcrk', 'AM', 87, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('\u00dcmit Davala', 'RM/RB', 85, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('Hasan \u015ea\u015f', 'RW/LW', 89, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('\u0130lhan Mans\u0131z', 'ST', 86, 'Turkey', 'Turkey', ['2002 WC Bronze'], 'Scored the golden goal vs Senegal in the quarterfinal.'),
      p('Hakan \u015e\u00fck\u00fcr', 'ST', 87, 'Turkey', 'Turkey', ['2002 WC Bronze'], 'Scored the fastest goal in World Cup history (10.8s).'),
      p('Arif Erdem', 'ST', 81, 'Turkey', 'Turkey', ['2002 WC Bronze']),
      p('Emre Bel\u00f6zo\u011flu', 'CM', 84, 'Turkey', 'Turkey', ['2002 WC Bronze']),
    ],
  },
  {
    id: 'brazil-2002',
    name: 'Brazil',
    type: 'national',
    year: 2002,
    era: '00s',
    manager: mgr('Luiz Felipe Scolari', 'Brazil', '3-5-2', 'Brazil 2002'),
    players: [
      p('Marcos', 'GK', 84, 'Brazil', 'Brazil', ['2002 World Cup']),
      p('L\u00facio', 'CB', 88, 'Brazil', 'Brazil', ['2002 World Cup']),
      p('Roque J\u00fanior', 'CB', 85, 'Brazil', 'Brazil', ['2002 World Cup']),
      p('Cafu', 'RB', 92, 'Brazil', 'Brazil', ['2002 World Cup'], 'Only player to appear in three consecutive World Cup finals.'),
      p('Roberto Carlos', 'LB', 93, 'Brazil', 'Brazil', ['2002 World Cup'], 'Thunderbolt left-back famous for his physics-defying free-kicks.'),
      p('Gilberto Silva', 'CM', 87, 'Brazil', 'Brazil', ['2002 World Cup']),
      p('Vampeta', 'CM', 81, 'Brazil', 'Brazil', ['2002 World Cup']),
      p('Ronaldinho', 'AM/LW', 94, 'Brazil', 'Brazil', ['2002 World Cup', '2x Ballon d\u2019Or'], 'Lobbed Seaman from 40 yards in the quarterfinal.'),
      p('Rivaldo', 'AM/ST', 93, 'Brazil', 'Brazil', ['2002 World Cup', 'Ballon d\u2019Or 1999']),
      p('Ronaldo Naz\u00e1rio', 'ST', 98, 'Brazil', 'Brazil', ['2002 World Cup', '2x Ballon d\u2019Or', '8 goals 2002'], 'O Fen\u00f4meno: scored both goals in the 2002 final to exorcise 1998.'),
    ],
  },
  {
    id: 'real-madrid-2003',
    name: 'Real Madrid',
    type: 'club',
    year: 2003,
    era: '00s',
    manager: mgr('Vicente del Bosque', 'Spain', '4-4-2', 'Real Madrid 2003'),
    players: [
      p('Iker Casillas', 'GK', 90, 'Spain', 'Real Madrid', ['UCL', 'La Liga']),
      p('Fernando Hierro', 'CB', 88, 'Spain', 'Real Madrid', ['UCL']),
      p('Ivan Helguera', 'CB', 85, 'Spain', 'Real Madrid', ['UCL']),
      p('Michel Salgado', 'RB', 86, 'Spain', 'Real Madrid', ['UCL']),
      p('Roberto Carlos', 'LB', 93, 'Brazil', 'Real Madrid', ['UCL']),
      p('Claude Mak\u00e9l\u00e9l\u00e9', 'DM/CM', 91, 'France', 'Real Madrid', ['UCL'], 'The midfield destroyer who redefined the holding role.'),
      p('Guti Hernandez', 'CM/AM', 86, 'Spain', 'Real Madrid', ['UCL']),
      p('David Beckham', 'RM', 89, 'England', 'Real Madrid', ['UCL'], 'Galactico signing and free-kick maestro.'),
      p('Luis Figo', 'RW', 92, 'Portugal', 'Real Madrid', ['Ballon d\u2019Or 2000', 'UCL']),
      p('Zinedine Zidane', 'AM', 96, 'France', 'Real Madrid', ['UCL', 'Ballon d\u2019Or'], 'Scored the legendary 2002 UCL final volley.'),
      p('Raul Gonzalez', 'ST', 91, 'Spain', 'Real Madrid', ['UCL'], 'Madrid\u2019s captain and record scorer of his era.'),
      p('Ronaldo Naz\u00e1rio', 'ST', 96, 'Brazil', 'Real Madrid', ['UCL', 'Ballon d\u2019Or']),
    ],
  },
  {
    id: 'fenerbahce-2008',
    name: 'Fenerbah\u00e7e',
    type: 'club',
    year: 2008,
    era: '00s',
    manager: mgr('Arthur Zico', 'Brazil', '4-3-3', 'Fenerbah\u00e7e 2008'),
    players: [
      p('Volkan Demirel', 'GK', 86, 'Turkey', 'Fenerbah\u00e7e', ['S\u00fcper Lig'], 'Fiery shot-stopper and long-time Fenerbah\u00e7e captain.'),
      p('Diego Lugano', 'CB', 88, 'Uruguay', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('Edu Dracena', 'CB', 85, 'Brazil', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('G\u00f6khan G\u00f6n\u00fcl', 'RB', 87, 'Turkey', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('Roberto Carlos', 'LB', 90, 'Brazil', 'Fenerbah\u00e7e', ['UCL']),
      p('Mehmet Aur\u00e9lio', 'CM', 87, 'Turkey', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('Sel\u00e7uk \u015eahin', 'CM', 79, 'Turkey', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('T\u00fcmer Metin', 'AM', 82, 'Turkey', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('Deivid de Souza', 'RW/ST', 86, 'Brazil', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('Alex de Souza', 'AM', 94, 'Brazil', 'Fenerbah\u00e7e', ['S\u00fcper Lig'], 'The greatest foreign player in Fenerbah\u00e7e history.'),
      p('Semih \u015eent\u00fcrk', 'ST', 85, 'Turkey', 'Fenerbah\u00e7e', ['S\u00fcper Lig'], 'Clutch striker of the 2008 UCL quarterfinal run.'),
      p('Mateja Ke\u017eman', 'ST', 84, 'Serbia', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
      p('Kaz\u0131m Kaz\u0131m', 'RW', 81, 'Turkey', 'Fenerbah\u00e7e', ['S\u00fcper Lig']),
    ],
  },
  {
    id: 'barcelona-2009',
    name: 'Barcelona',
    type: 'club',
    year: 2009,
    era: '00s',
    manager: mgr('Pep Guardiola', 'Spain', '4-3-3', 'Barcelona 2009'),
    players: [
      p('V\u00edctor Vald\u00e9s', 'GK', 86, 'Spain', 'Barcelona', ['UCL', 'La Liga']),
      p('Gerard Piqu\u00e9', 'CB', 89, 'Spain', 'Barcelona', ['UCL', 'World Cup 2010']),
      p('Carles Puyol', 'CB', 92, 'Spain', 'Barcelona', ['UCL', 'World Cup 2010'], 'Indomitable captain of the greatest club side ever.'),
      p('Dani Alves', 'RB', 91, 'Brazil', 'Barcelona', ['UCL']),
      p('Eric Abidal', 'LB', 85, 'France', 'Barcelona', ['UCL']),
      p('Sergio Busquets', 'DM/CM', 89, 'Spain', 'Barcelona', ['UCL', 'World Cup 2010'], 'The metronome who made the impossible look simple.'),
      p('Xavi Hern\u00e1ndez', 'CM', 95, 'Spain', 'Barcelona', ['UCL', 'World Cup 2010'], 'The conductor of tiki-taka.'),
      p('Andr\u00e9s Iniesta', 'CM/AM', 95, 'Spain', 'Barcelona', ['UCL', 'World Cup 2010'], 'Scored the 2010 World Cup-winning goal.'),
      p('Thierry Henry', 'LW', 91, 'France', 'Barcelona', ['UCL']),
      p('Samuel Eto\u2019o', 'ST', 92, 'Cameroon', 'Barcelona', ['UCL']),
      p('Lionel Messi', 'RW/ST', 97, 'Argentina', 'Barcelona', ['UCL', '8x Ballon d\u2019Or'], 'The greatest of all time; headed the decisive goal in the 2009 final.'),
    ],
  },
  {
    id: 'spain-2010',
    name: 'Spain',
    type: 'national',
    year: 2010,
    era: '10s',
    manager: mgr('Vicente del Bosque', 'Spain', '4-2-3-1', 'Spain 2010'),
    players: [
      p('Iker Casillas', 'GK', 94, 'Spain', 'Spain', ['2010 World Cup', 'Euro 2008', 'Euro 2012'], 'San Iker, captain of Spain\u2019s golden generation.'),
      p('Gerard Piqu\u00e9', 'CB', 90, 'Spain', 'Spain', ['2010 World Cup']),
      p('Carles Puyol', 'CB', 92, 'Spain', 'Spain', ['2010 World Cup'], 'Headed the winning goal in the 2010 semifinal.'),
      p('Sergio Ramos', 'RB', 91, 'Spain', 'Spain', ['2010 World Cup']),
      p('Joan Capdevila', 'LB', 86, 'Spain', 'Spain', ['2010 World Cup']),
      p('Sergio Busquets', 'DM/CM', 89, 'Spain', 'Spain', ['2010 World Cup']),
      p('Xabi Alonso', 'CM', 91, 'Spain', 'Spain', ['2010 World Cup']),
      p('Xavi Hern\u00e1ndez', 'CM', 95, 'Spain', 'Spain', ['2010 World Cup']),
      p('Andr\u00e9s Iniesta', 'CM/LW', 95, 'Spain', 'Spain', ['2010 World Cup'], 'Scored the goal that won Spain its first World Cup.'),
      p('Cesc F\u00e0bregas', 'AM', 89, 'Spain', 'Spain', ['2010 World Cup']),
      p('David Villa', 'ST/LW', 92, 'Spain', 'Spain', ['2010 World Cup'], 'Spain\u2019s all-time top scorer.'),
      p('Fernando Torres', 'ST', 89, 'Spain', 'Spain', ['2010 World Cup', 'Euro 2008']),
    ],
  },
  {
    id: 'germany-2014',
    name: 'Germany',
    type: 'national',
    year: 2014,
    era: '10s',
    manager: mgr('Joachim L\u00f6w', 'Germany', '4-3-3', 'Germany 2014'),
    players: [
      p('Manuel Neuer', 'GK', 95, 'Germany', 'Germany', ['2014 World Cup'], 'Redefined the sweeper-keeper role and won the Golden Glove.'),
      p('Mats Hummels', 'CB', 91, 'Germany', 'Germany', ['2014 World Cup']),
      p('J\u00e9r\u00f4me Boateng', 'CB', 89, 'Germany', 'Germany', ['2014 World Cup']),
      p('Philipp Lahm', 'RB/CM', 93, 'Germany', 'Germany', ['2014 World Cup'], 'Captain and tactical chameleon.'),
      p('Benedikt H\u00f6wedes', 'LB', 85, 'Germany', 'Germany', ['2014 World Cup']),
      p('Sami Khedira', 'CM', 87, 'Germany', 'Germany', ['2014 World Cup']),
      p('Bastian Schweinsteiger', 'CM', 92, 'Germany', 'Germany', ['2014 World Cup'], 'Bloodied warrior of the 2014 final.'),
      p('Toni Kroos', 'CM', 91, 'Germany', 'Germany', ['2014 World Cup']),
      p('Mesut \u00d6zil', 'AM', 90, 'Germany', 'Germany', ['2014 World Cup']),
      p('Thomas M\u00fcller', 'RW/ST', 91, 'Germany', 'Germany', ['2014 World Cup'], 'The original "Raumdeuter" (space interpreter).'),
      p('Miroslav Klose', 'ST', 87, 'Germany', 'Germany', ['2014 World Cup'], 'All-time leading World Cup goalscorer with 16.'),
    ],
  },
  {
    id: 'real-madrid-2017',
    name: 'Real Madrid',
    type: 'club',
    year: 2017,
    era: '10s',
    manager: mgr('Zinedine Zidane', 'France', '4-3-3', 'Real Madrid 2017'),
    players: [
      p('Keylor Navas', 'GK', 88, 'Costa Rica', 'Real Madrid', ['3x UCL']),
      p('Sergio Ramos', 'CB', 92, 'Spain', 'Real Madrid', ['UCL', 'World Cup 2010'], 'Clutch captain famous for last-minute goals.'),
      p('Rapha\u00ebl Varane', 'CB', 89, 'France', 'Real Madrid', ['UCL', 'World Cup 2018']),
      p('Dani Carvajal', 'RB', 88, 'Spain', 'Real Madrid', ['UCL']),
      p('Marcelo', 'LB', 91, 'Brazil', 'Real Madrid', ['UCL'], 'Most decorated player in Real Madrid history.'),
      p('Casemiro', 'CM', 90, 'Brazil', 'Real Madrid', ['UCL']),
      p('Toni Kroos', 'CM', 93, 'Germany', 'Real Madrid', ['UCL', 'World Cup 2014']),
      p('Luka Modri\u0107', 'CM', 94, 'Croatia', 'Real Madrid', ['UCL', 'Ballon d\u2019Or 2018'], 'Ended the Messi-Ronaldo Ballon d\u2019Or duopoly.'),
      p('Isco', 'AM', 88, 'Spain', 'Real Madrid', ['UCL']),
      p('Karim Benzema', 'ST', 91, 'France', 'Real Madrid', ['UCL', 'Ballon d\u2019Or 2022']),
      p('Cristiano Ronaldo', 'ST/LW', 97, 'Portugal', 'Real Madrid', ['5x UCL', '5x Ballon d\u2019Or'], 'UCL\u2019s all-time top scorer and a relentless winner.'),
    ],
  },
  {
    id: 'france-2018',
    name: 'France',
    type: 'national',
    year: 2018,
    era: '10s',
    manager: mgr('Didier Deschamps', 'France', '4-2-3-1', 'France 2018'),
    players: [
      p('Hugo Lloris', 'GK', 89, 'France', 'France', ['2018 World Cup'], 'Captain who lifted the 2018 trophy.'),
      p('Rapha\u00ebl Varane', 'CB', 90, 'France', 'France', ['2018 World Cup', 'UCL']),
      p('Samuel Umtiti', 'CB', 88, 'France', 'France', ['2018 World Cup'], 'Headed the winning goal in the 2018 semifinal.'),
      p('Lucas Hernandez', 'LB', 86, 'France', 'France', ['2018 World Cup']),
      p('Benjamin Pavard', 'RB', 85, 'France', 'France', ['2018 World Cup'], 'Scored the goal of the tournament vs Argentina.'),
      p('N\u2019Golo Kant\u00e9', 'CM', 92, 'France', 'France', ['2018 World Cup'], 'The tireless engine who covers every blade of grass.'),
      p('Paul Pogba', 'CM', 90, 'France', 'France', ['2018 World Cup']),
      p('Blaise Matuidi', 'LM/CM', 87, 'France', 'France', ['2018 World Cup']),
      p('Antoine Griezmann', 'AM/ST', 91, 'France', 'France', ['2018 World Cup']),
      p('Kylian Mbapp\u00e9', 'RW/ST', 94, 'France', 'France', ['2018 World Cup', 'Young Player Award'], 'Teenage sensation who scored in the 2018 final.'),
      p('Olivier Giroud', 'ST', 85, 'France', 'France', ['2018 World Cup']),
    ],
  },
  {
    id: 'argentina-2022',
    name: 'Argentina',
    type: 'national',
    year: 2022,
    era: '20s',
    manager: mgr('Lionel Scaloni', 'Argentina', '4-3-3', 'Argentina 2022'),
    players: [
      p('Emiliano Mart\u00ednez', 'GK', 89, 'Argentina', 'Argentina', ['2022 World Cup', 'Golden Glove'], 'Penalty-shootout hero and Golden Glove winner.'),
      p('Cristian Romero', 'CB', 88, 'Argentina', 'Argentina', ['2022 World Cup']),
      p('Nicol\u00e1s Otamendi', 'CB', 86, 'Argentina', 'Argentina', ['2022 World Cup']),
      p('Nahuel Molina', 'RB', 85, 'Argentina', 'Argentina', ['2022 World Cup']),
      p('Nicol\u00e1s Tagliafico', 'LB', 85, 'Argentina', 'Argentina', ['2022 World Cup']),
      p('Rodrigo De Paul', 'CM', 87, 'Argentina', 'Argentina', ['2022 World Cup']),
      p('Enzo Fern\u00e1ndez', 'CM', 87, 'Argentina', 'Argentina', ['2022 World Cup', 'Young Player Award']),
      p('Alexis Mac Allister', 'CM', 87, 'Argentina', 'Argentina', ['2022 World Cup']),
      p('\u00c1ngel Di Mar\u00eda', 'RW/LW', 89, 'Argentina', 'Argentina', ['2022 World Cup'], 'Scored in the 2022 final and many a final before.'),
      p('Lionel Messi', 'RW/ST', 99, 'Argentina', 'Argentina', ['2022 World Cup', '8x Ballon d\u2019Or', 'Golden Ball'], 'Completed football immortality by winning the World Cup.'),
      p('Juli\u00e1n \u00c1lvarez', 'ST', 87, 'Argentina', 'Argentina', ['2022 World Cup']),
    ],
  },
  {
    id: 'real-madrid-2024',
    name: 'Real Madrid',
    type: 'club',
    year: 2024,
    era: '20s',
    manager: mgr('Carlo Ancelotti', 'Italy', '4-3-3', 'Real Madrid 2024'),
    players: [
      p('Thibaut Courtois', 'GK', 92, 'Belgium', 'Real Madrid', ['UCL'], 'Man of the match in the 2022 UCL final.'),
      p('Antonio R\u00fcdiger', 'CB', 90, 'Germany', 'Real Madrid', ['UCL']),
      p('\u00c9der Milit\u00e3o', 'CB', 87, 'Brazil', 'Real Madrid', ['UCL']),
      p('Dani Carvajal', 'RB', 88, 'Spain', 'Real Madrid', ['UCL'], 'Scored the opener in the 2024 final.'),
      p('Ferland Mendy', 'LB', 86, 'France', 'Real Madrid', ['UCL']),
      p('Aur\u00e9lien Tchou\u00e9meni', 'CM', 87, 'France', 'Real Madrid', ['UCL']),
      p('Federico Valverde', 'CM', 90, 'Uruguay', 'Real Madrid', ['UCL']),
      p('Jude Bellingham', 'AM/CM', 94, 'England', 'Real Madrid', ['UCL'], 'Debut-season sensation who took LaLiga by storm.'),
      p('Toni Kroos', 'CM', 91, 'Germany', 'Real Madrid', ['UCL', 'World Cup 2014']),
      p('Rodrygo Goes', 'RW/ST', 89, 'Brazil', 'Real Madrid', ['UCL']),
      p('Vin\u00edcius J\u00fanior', 'LW', 95, 'Brazil', 'Real Madrid', ['UCL'], 'Scored the winner in the 2022 final.'),
    ],
  },
  {
    id: 'france-2026',
    name: 'France',
    type: 'national',
    year: 2026,
    era: '20s',
    manager: mgr('Didier Deschamps', 'France', '4-2-3-1', 'France 2026'),
    players: [
      p('Mike Maignan', 'GK', 89, 'France', 'France', ['Serie A']),
      p('William Saliba', 'CB', 90, 'France', 'France', []),
      p('Ibrahima Konat\u00e9', 'CB', 86, 'France', 'France', ['UCL']),
      p('Th\u00e9o Hernandez', 'LB', 87, 'France', 'France', ['Serie A']),
      p('Jules Kound\u00e9', 'RB', 86, 'France', 'France', ['La Liga']),
      p('Aur\u00e9lien Tchou\u00e9meni', 'DM/CM', 88, 'France', 'France', ['UCL']),
      p('Eduardo Camavinga', 'CM', 87, 'France', 'France', ['UCL']),
      p('Warren Za\u00efre-Emery', 'CM/AM', 84, 'France', 'France', []),
      p('Kylian Mbapp\u00e9', 'ST/LW', 95, 'France', 'France', ['2018 World Cup'], 'France\u2019s talisman and captain entering his prime.'),
      p('Ousmane Demb\u00e9l\u00e9', 'RW', 88, 'France', 'France', ['Ballon d\u2019Or 2025']),
      p('Bradley Barcola', 'LW', 84, 'France', 'France', []),
    ],
  },
  {
    id: 'brazil-2026',
    name: 'Brazil',
    type: 'national',
    year: 2026,
    era: '20s',
    manager: mgr('Dorival J\u00fanior', 'Brazil', '4-2-3-1', 'Brazil 2026'),
    players: [
      p('Alisson', 'GK', 90, 'Brazil', 'Brazil', ['UCL', 'Copa Am\u00e9rica']),
      p('Gabriel Magalh\u00e3es', 'CB', 87, 'Brazil', 'Brazil', []),
      p('Marquinhos', 'CB', 88, 'Brazil', 'Brazil', ['UCL']),
      p('Guilherme Arana', 'LB', 81, 'Brazil', 'Brazil', []),
      p('Danilo', 'RB', 82, 'Brazil', 'Brazil', ['UCL']),
      p('Bruno Guimar\u00e3es', 'CM', 87, 'Brazil', 'Brazil', []),
      p('Andr\u00e9', 'CM/DM', 83, 'Brazil', 'Brazil', []),
      p('Lucas Paquet\u00e1', 'AM', 85, 'Brazil', 'Brazil', []),
      p('Rodrygo Goes', 'RW/ST', 88, 'Brazil', 'Brazil', ['UCL']),
      p('Vin\u00edcius J\u00fanior', 'LW', 92, 'Brazil', 'Brazil', ['UCL'], 'Brazil\u2019s creative force and main threat.'),
      p('Endrick', 'ST', 82, 'Brazil', 'Brazil', [], 'The teenage jewel and future of the Sele\u00e7\u00e3o.'),
    ],
  },
  {
    id: 'england-2026',
    name: 'England',
    type: 'national',
    year: 2026,
    era: '20s',
    manager: mgr('Thomas Tuchel', 'Germany', '4-2-3-1', 'England 2026'),
    players: [
      p('Jordan Pickford', 'GK', 85, 'England', 'England', []),
      p('John Stones', 'CB', 86, 'England', 'England', ['UCL']),
      p('Marc Gu\u00e9hi', 'CB', 83, 'England', 'England', []),
      p('Luke Shaw', 'LB', 83, 'England', 'England', []),
      p('Trent Alexander-Arnold', 'RB', 87, 'England', 'England', ['UCL'], 'Visionary passing full-back with a wand of a right foot.'),
      p('Declan Rice', 'DM/CM', 88, 'England', 'England', []),
      p('Kobbie Mainoo', 'CM', 82, 'England', 'England', [], 'Breakout midfield talent and composure beyond his years.'),
      p('Jude Bellingham', 'AM/CM', 91, 'England', 'England', ['UCL'], 'England\u2019s generational midfield superstar.'),
      p('Bukayo Saka', 'RW', 89, 'England', 'England', []),
      p('Phil Foden', 'LW/AM', 89, 'England', 'England', ['UCL', 'PL POTY']),
      p('Harry Kane', 'ST', 90, 'England', 'England', [], 'England\u2019s all-time leading goalscorer and captain.'),
      p('Cole Palmer', 'AM/RW', 86, 'England', 'England', [], 'Ice-cold finisher and creative spark.'),
    ],
  },
]

export const ALL_MANAGERS: Manager[] = TEAMS.map((t) => t.manager)
